name: tcr_pmhc_benchmark_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=24.0
  - cudatoolkit=11.3
  - hydra-core==1.3.2
  - ipykernel=6.29.3
  - ipython=8.12.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - matplotlib=3.7.2
  - numpy=1.24.3
  - omegaconf==2.3.0
  - pandas=1.4.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - tqdm==4.64.0

  - pip:
      - editdistance==0.6.2
      - confidenceinterval==1.0.4
      - seaborn==0.13.2
      - transformers==4.23.1
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.12.0+cu113
