# Model type.
model_type: RandomForestClassifier
# XGB learning rate.
learning_rate: 0.1
# Number of estimators.
n_estimators: 40
# Subsample ratio.
subsample: 1.0
# Minimum number of samples to split a node.
min_samples_split: 2
# Minimum samples per leaf node.
min_samples_leaf: 1
# Minimum fraction of samples to be considered as a valid leaf.
min_weight_fraction_leaf: 0.0
# Maximum depth of a tree.
max_depth: 5
# Minimum decrease in impurity metric to make a split.
min_impurity_decrease: 0.0
# Verbosity level.
verbose: 1
# Seed.
random_state: 42
